#See https://github.com/swoole/docker-swoole/tree/master/examples
services:
  app:
    container_name: swoole_server
    image: openswoole/swoole:25.2-php8.4
    ports:
      - "8003:8003"
    volumes:
      - .:/var/www/
#    working_dir: /var/www/
#    command: php /var/www/index.php
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
      SWOOLE_SERVER_PORT: ${SWOOLE_SERVER_PORT}
      SWOOLE_SERVER_HOST: ${SWOOLE_SERVER_HOST}
      PHP_IDE_CONFIG: "serverName=application"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=host.docker.internal remote_port=9000"
