# See https://github.com/swoole/docker-swoole?tab=readme-ov-file
#FROM phpswoole/swoole:php8.1-zts-dev
FROM openswoole/swoole:25.2-php8.4
# Install PDO MySQL extension
RUN docker-php-ext-install pdo_mysql